### ISSUE TITLE
致命错误

### ISSUE THREAD

**Issue by eonun** [sun11/hexo-renderer-kramed#8]
我在hexo文章中使用到 `{#rgb}` 出现以下错误，查下来是 `{#` 导致的错误

FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  Error: expected end of comment, got end of file
    at Object._prettifyError (/home/eonun/testhexo/node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/home/eonun/testhexo/node_modules/nunjucks/src/environment.js:542:21)
    at Environment.renderString (/home/eonun/testhexo/node_modules/nunjucks/src/environment.js:380:17)
    at Promise.fromCallback.cb (/home/eonun/testhexo/node_modules/hexo/lib/extend/tag.js:123:48)
    at tryCatcher (/home/eonun/testhexo/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:209:30)
    at Tag.render (/home/eonun/testhexo/node_modules/hexo/lib/extend/tag.js:123:18)
    at Object.onRenderEnd (/home/eonun/testhexo/node_modules/hexo/lib/hexo/post.js:280:20)
    at Promise.then.then.result (/home/eonun/testhexo/node_modules/hexo/lib/hexo/render.js:64:19)
    at tryCatcher (/home/eonun/testhexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  Error: expected end of comment, got end of file
    at Object._prettifyError (/home/eonun/testhexo/node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/home/eonun/testhexo/node_modules/nunjucks/src/environment.js:542:21)
    at Environment.renderString (/home/eonun/testhexo/node_modules/nunjucks/src/environment.js:380:17)
    at Promise.fromCallback.cb (/home/eonun/testhexo/node_modules/hexo/lib/extend/tag.js:123:48)
    at tryCatcher (/home/eonun/testhexo/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:209:30)
    at Tag.render (/home/eonun/testhexo/node_modules/hexo/lib/extend/tag.js:123:18)
    at Object.onRenderEnd (/home/eonun/testhexo/node_modules/hexo/lib/hexo/post.js:280:20)
    at Promise.then.then.result (/home/eonun/testhexo/node_modules/hexo/lib/hexo/render.js:64:19)
    at tryCatcher (/home/eonun/testhexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/eonun/testhexo/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/eonun/testhexo/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by eonun** [comment]
刚才查出了是`hexo` 本身的错误
